os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode7.3
install:
  - bash TestRedis/install_redis_local.sh
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"
script:
  - export PATH="$PWD/redis-stable/src/:$PATH"
  - make redis-start
  - swift build
  - swift test
  - make example
notifications:
  email:
    on_success: never
    on_failure: change


