os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode7.3
install:
  - bash TestRedis/install_redis_local.sh
  - curl -sL https://gist.github.com/kylef/5c0475ff02b7c7671d2a/raw/621ef9b29bbb852fdfd2e10ed147b321d792c1e4/swiftenv-install.sh | bash
script:
  - . ~/.swiftenv/init
  - export PATH="$PWD/redis-stable/src/:$PATH"
  - make redis-start
  - git clone https://github.com/apple/swift-package-manager swiftpm
  - cd swiftpm && git checkout 0373b84 && cd ../
  - swiftpm/Utilities/bootstrap
  - ${PWD}/swiftpm/.build/debug/swift-build
  - ${PWD}/swiftpm/.build/debug/swift-test
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make xctest; fi
  - make example
notifications:
  email:
    on_success: never
    on_failure: change



